[versions]
agp = "9.0.1"
kotlin = "2.3.10"
ksp = "2.3.6"
joor = "0.9.15"

[libraries]
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
joor = { module = "org.jooq:joor", version.ref = "joor" }

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
agp-lib = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
